create table
  public.barrels (
    id bigint generated by default as identity not null,
    type text null,
    ml bigint null default '0'::bigint,
    constraint barrels_pkey primary key (id)
  ) tablespace pg_default;

  create table
  public.cart_items (
    id bigint generated by default as identity not null,
    cart_id bigint not null,
    item_sku text null default ''::text,
    quantity bigint null,
    customer_payment text null,
    price bigint null,
    constraint cart_items_pkey primary key (id)
  ) tablespace pg_default;

  create table
  public.carts (
    id bigint generated by default as identity not null,
    name text null default ''::text,
    class text null,
    constraint carts_pkey primary key (id)
  ) tablespace pg_default;

  create table
  public.carts (
    id bigint generated by default as identity not null,
    name text null default ''::text,
    class text null,
    constraint carts_pkey primary key (id)
  ) tablespace pg_default;

  create table
  public.global_inventory (
    id bigint generated by default as identity not null,
    gold integer null default 100,
    constraint global_inventory_pkey primary key (id)
  ) tablespace pg_default;

  create table
  public.potions (
    id bigint generated by default as identity not null,
    potion_sku text not null default ''::text,
    name text null,
    quantity bigint null,
    price bigint null,
    red_ml bigint null,
    green_ml bigint null,
    blue_ml bigint null,
    dark_ml bigint null,
    constraint potions_pkey primary key (id)
  ) tablespace pg_default;

  create table
  public.visitors (
    id bigint generated by default as identity not null,
    name character varying null default ''::character varying,
    class character varying null default ''::character varying,
    level real null default '0'::real,
    constraint visitors_pkey primary key (id)
  ) tablespace pg_default;